
import { Bias, Products } from '../../shared/constants.js';

const products = [
    {
        "id": 1,
        "name": "Room Standee",
        "category": Products.STANDEE,
        "price": 550,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905261/roomStandee1_ye28yd.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905261/roomStandee2_awuuur.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905261/roomStandee3_ghbboi.jpg"
        ],
        "members": [Bias.OT7],
        "description": "Brighten up your space with this beautiful BTS Life Goes On Room Standee 🌸 A perfect keepsake to feel their warmth and love every day 💜"
    },
    {
        "id": 2,
        "name": "Album Frame",
        "category": Products.OTHER,
        "price": 500,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ['https://res.cloudinary.com/dxerpx7nt/image/upload/v1754908878/albumFrame1_fdkvdd.jpg'],
        "members": [Bias.OT7],
        "description": "Display your BTS journey with this custom album frame! Comes with 35 beautifully designed album tiles, and you can showcase 25 at a time — mix and match your favorite eras anytime. Frame of your choice included! 💜"
    },
    {
        "id": 3,
        "name": "Taehyung Paris Photocards",
        "category": Products.PHOTOCARD,
        "price": 200,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905268/taeParisPhotos1_eage0b.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905268/taeParisPhotos2_mbvzdw.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905268/taeParisPhotos3_uaz41g.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905269/taeParisPhotos4_os47k4.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905270/taeParisPhotos5_atb3rd.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905269/taeParisPhotos6_v0o205.jpg"
        ],
        "members": [Bias.V],
        "description": "Bring home the Parisian charm with Taehyung’s stunning photocards 💜 Printed on one side with a glossy laminated finish for that premium shine. Perfect for collectors and BTS lovers alike!"
    },
    {
        "id": 4,
        "name": "TaeKook Couple Heart Keychain",
        "category": Products.KEYCHAIN,
        "price": 320,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905265/taeKookCoupleHeartKeychain_rpmjym.jpg"],
        "members": [Bias.JUNGKOOK, Bias.V],
        "description": "Celebrate the bond of TaeKook with this adorable heart keychain 💕 Crafted with love — perfect for every true ARMY!"
    },
    {
        "id": 5,
        "name": "Hobi Acorn Charm",
        "category": Products.OTHER,
        "price": 90,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905249/hobiAcronCharmBack_cqyypi.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905248/hobiAcronCharmFront_vo80ab.jpg"
        ],
        "members": [Bias.JHOPE],
        "description": "Shine like Hobi with this vibrant J-Hope acronym charm 🌟 A cheerful little piece to brighten your day — just like our sunshine!"
    },
    {
        "id": 6,
        "name": "Mic Keychain",
        "category": Products.KEYCHAIN,
        "price": 320,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905250/micKeychain1_pixzob.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905252/micKeychain2_uviahr.jpg"
        ],
        "members": [Bias.OT7],
        "description": "Carry a piece of the stage with this dazzling holographic mic keychain 🎤✨ Perfect for ARMYs who vibe with every BTS performance!"
    },
    {
        "id": 7,
        "name": "JK Dance",
        "category": Products.ACRYLIC_PIN,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905261/jKDanceAcrylicPin_jkm5wp.jpg"],
        "members": [Bias.JUNGKOOK],
        "description": "Feel the energy of Jungkook’s moves with this holographic dance pin 💃✨ A sparkling tribute to the Golden Maknae’s iconic stage presence!"
    },
    {
        "id": 8,
        "name": "Tae Dance",
        "category": Products.ACRYLIC_PIN,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905265/taeDanceAcrylicPin_jigo2f.jpg"],
        "members": [Bias.V],
        "description": "Grace meets charm in this Tae Dance Acrylic Pin 💜🕺 A dreamy collectible capturing V’s iconic moves and charisma!"
    },
    {
        "id": 9,
        "name": "Tae Squid Pin",
        "category": Products.ACRYLIC_PIN,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905269/taeSquidPin_basrvk.jpg"],
        "members": [Bias.V],
        "description": "V meets Squid Game in this playful costume pin 🎭 A quirky crossover collectible for fans of drama and charm!"
    },
    {
        "id": 10,
        "name": "Indigo Keychain",
        "category": Products.KEYCHAIN,
        "price": 270,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905251/indigoKeychain1_qwbigj.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905252/indigoKeychain2_z0kibs.jpg"
        ],
        "members": [Bias.RM],
        "description": "Inspired by RM’s Indigo era — this keychain is calm, deep, and soulful 🎧💙A perfect piece for those who cherish his art and authenticity."
    },
    {
        "id": 11,
        "name": "Tae Gentleman",
        "category": Products.ACRYLIC_PIN,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905265/taeGentleman_p9q7du.jpg"],
        "members": [Bias.V],
        "description": "Elegance meets charm with this Tae Gentleman Acrylic Pin 🤵💜 A dashing collectible for those who adore V’s timeless style."
    },
    {
        "id": 12,
        "name": "TaeKook Keychain Holder",
        "category": Products.OTHER,
        "price": 450,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905267/taeKookKeychainHolder1_bvyime.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905267/taeKookKeychainHolder2_m9zyfk.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905267/taeKookKeychainHolder3_ikjtvu.jpg"
        ],
        "members": [Bias.V, Bias.JUNGKOOK],
        "description": "Keep your keys close with this adorable TaeKook Keychain Holder 💜🔐 A perfect duo to hold your heart — and your keys!"
    },
    {
        "id": 108,
        "name": "Suga Butt",
        "category": Products.ACRYLIC_PIN,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905263/sugaButt_r4h3xs.jpg"],
        "members": [Bias.SUGA],
        "description": "A fun little tribute to Yoongi’s iconic charm 🍑💜 Because even SUGA’s sass has a fanbase of its own!"
    },
    {
        "id": 13,
        "name": "Hobi Mic Drop",
        "category": Products.ACRYLIC_PIN,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905250/hobiMicDrop_e4u89w.jpg"],
        "members": [Bias.JHOPE],
        "description": "Bring the fire with this Hobi Mic Drop piece 🎤🔥 Full of energy, swag, and sunshine — just like J-Hope!"
    },
    {
        "id": 14,
        "name": "VMinKook AYS Standee",
        "category": Products.STANDEE,
        "price": 350,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905271/vMinKookAYSStandee1_tgi7ub.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905271/vMinKookAYSStandee2_n7rfcl.jpg"
        ],
        "members": [Bias.JUNGKOOK, Bias.V, Bias.JIMIN],
        "description": "Relive the legendary ‘Are you sure?’ moment with this VMinKook standee 💜🎬 A must-have for every ARMY who lives for their chaotic love!"
    },
    {
        "id": 15,
        "name": "Wind Chime Keychain",
        "category": Products.KEYCHAIN,
        "price": 270,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905272/windChime_gv65uw.jpg"],
        "members": [Bias.RM],
        "description": "Inspired by Namjoon’s calm and nature-loving soul 🌿🔔 This wind chime keychain brings peace wherever you go."
    },
    {
        "id": 16,
        "name": "Monalisa Frame Keychain",
        "category": Products.PC_HOLDER,
        "price": 280,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905255/monalisaFrame1_jtnn33.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905256/monalisaFrame2_pt9hhe.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905256/monalisaFrame3_xvhq9h.jpg"
        ],
        "members": [Bias.JHOPE],
        "description": "A masterpiece in your pocket! 🎨 Featuring Hobi in a vintage Monalisa-style frame, this keychain is cute, classy, and full of charm. A must-have for every sunshine fan 💛"
    },
    {
        "id": 17,
        "name": "TaeKook Phone Holder",
        "category": Products.KEYCHAIN,
        "price": 460,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905267/taeKookPhoneHolder1_hxfynn.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905267/taeKookPhoneHolder2_cxfoze.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905267/taeKookPhoneHolder3_ixpkfl.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905267/taeKookPhoneHolder4_nclvnm.jpg"
        ],
        "members": [Bias.V, Bias.JUNGKOOK],
        "description": "Keep your bias duo close while you scroll 💜📱 This TaeKook phone holder blends love with everyday ease!"
    },
    {
        "id": 18,
        "name": "7 Keychain",
        "category": Products.KEYCHAIN,
        "price": 270,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905262/sevenKeychain1_qh3plw.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905262/sevenKeychain2_n3fp4q.jpg"
        ],
        "members": [Bias.OT7],
        "description": "Celebrating OT7 love 💜 A sleek and stylish keychain with the number 7 — symbolizing unity, forever bond, and BTS as one. A perfect charm for every ARMY!"
    },
    {
        "id": 19,
        "name": "KillintGirl Photocards",
        "category": Products.PHOTOCARD,
        "price": 6,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905243/killinItGirlHobiPic1_awnrtl.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905243/killinItGirlHobiPic2_xs4bf5.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905243/killinItGirlHobiPic3_egxtdq.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905244/killinItGirlHobiPic4_s2hfb5.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905245/killinItGirlHobiPic5_hjcne9.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905245/killinItGirlHobiPic6_u8yewl.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905245/killinItGirlHobiPic7_x3r3pp.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905246/killinItGirlHobiPic8_hvv9ii.jpg"
        ],
        "members": [Bias.JHOPE],
        "description": "Fierce, flawless, and full of attitude 🔥📸 These Killin’t Girl photocards are made to slay your collection!"
    },
    {
        "id": 20,
        "name": "JK Military",
        "category": Products.KEYCHAIN,
        "price": 220,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905251/militaryKeychain1_zkkq42.jpg"],
        "members": [Bias.JUNGKOOK],
        "description": "Show your unwavering support for Jungkook with this military-themed keychain. A strong and stylish accessory for every ARMY."
    },
    {
        "id": 21,
        "name": "JIN Military",
        "category": Products.KEYCHAIN,
        "price": 220,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905252/militaryKeychain2_uax2gu.jpg"],
        "members": [Bias.JIN],
        "description": "Keep Jin close to your heart with this special military-themed keychain. A timeless piece to show your love and support."
    },
    {
        "id": 22,
        "name": "V Military",
        "category": Products.KEYCHAIN,
        "price": 220,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905253/militaryKeychain3_prqmwm.jpg"],
        "members": [Bias.V],
        "description": "A stylish nod to V's dedication and service. This military-themed keychain is the perfect way to show your support."
    },
    {
        "id": 23,
        "name": "JIMIN Military",
        "category": Products.KEYCHAIN,
        "price": 220,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905253/militaryKeychain4_tzazzg.jpg"],
        "members": [Bias.JIMIN],
        "description": "A beautiful keychain to honor Jimin's service. Carry a symbol of your pride and support wherever you go."
    },
    {
        "id": 24,
        "name": "JHOPE Military",
        "category": Products.KEYCHAIN,
        "price": 220,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905254/militaryKeychain5_eboa5i.jpg"],
        "members": [Bias.JHOPE],
        "description": "Show your love for our sunshine, J-Hope, with this military-themed keychain. A symbol of hope and strength."
    },
    {
        "id": 25,
        "name": "RM Military",
        "category": Products.KEYCHAIN,
        "price": 220,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905254/militaryKeychain6_vjvoyw.jpg"],
        "members": [Bias.RM],
        "description": "A sophisticated keychain for our esteemed leader, RM. Show your support and admiration with this military-themed accessory."
    },
    {
        "id": 26,
        "name": "SUGA Military",
        "category": Products.KEYCHAIN,
        "price": 220,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905254/militaryKeychain7_xaxa13.jpg"],
        "members": [Bias.SUGA],
        "description": "A cool and understated keychain to show your support for Suga. A perfect, meaningful accessory for any fan."
    },
    {
        "id": 27,
        "name": "Tae Winter Bear",
        "category": Products.KEYCHAIN,
        "price": 450,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905270/taeWinterBear_yjlzo2.png"],
        "members": [Bias.V],
        "description": "Inspired by V's soulful 'Winter Bear,' this keychain is a gentle and heartwarming accessory. A perfect piece to carry a little bit of his warmth with you."
    },
    {
        "id": 28,
        "name": "Mic Standee",
        "category": Products.STANDEE,
        "price": 420,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905251/micStandee_klmn3g.png"],
        "members": [Bias.OT7],
        "description": "Bring the concert vibes home with this stunning Mic Standee. A tribute to BTS's powerful performances and the iconic symbol of their connection with ARMY."
    },
    {
        "id": 29,
        "name": "HOTStage Keychain",
        "category": Products.KEYCHAIN,
        "price": 420,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905251/HOTStageKeychain_ak7zfm.jpg"],
        "members": [Bias.JHOPE],
        "description": "Capture the fire of J-Hope's on-stage presence with this 'Hope on the Street' keychain. A vibrant and energetic accessory for fans of his incredible dance moves."
    },
    {
        "id": 30,
        "name": "Suga 3in1 Stand",
        "category": Products.STANDEE,
        "price": 420,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905264/suga3in1Standee_eoutj5.jpg"],
        "members": [Bias.SUGA],
        "description": "Three times the charm, three times the style. This Suga 3-in-1 standee is a versatile and dynamic piece to celebrate the many facets of our genius producer."
    },
    {
        "id": 31,
        "name": "Military Set Keychain",
        "category": Products.KEYCHAIN,
        "price": 1200,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905257/militarySetKeychain_e5ch6n.jpg"],
        "members": [Bias.OT7],
        "description": "The ultimate tribute to their service. This complete Military Set Keychain honors all seven members, a must-have for ARMYs who support them as one."
    },
    {
        "id": 32,
        "name": "Heart Shakers",
        "category": Products.OTHER,
        "price": 150,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905248/heartShakers_pcf5rc.jpg"],
        "members": [Bias.OT7],
        "description": "Shake up your world with a little love from BTS! These Heart Shakers are a fun and charming way to show your affection for all seven members."
    },
    {
        "id": 33,
        "name": "RPWP Keychain",
        "category": Products.KEYCHAIN,
        "price": 260,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905262/rpwpKeychain_sfsdge.jpg"],
        "members": [Bias.RM],
        "description": "Inspired by RM's 'Right Place, Wrong Person,' this keychain is a tribute to his artistic and introspective journey. A thoughtful piece for any true fan."
    },
    {
        "id": 34,
        "name": "Tae Type1 Keychain",
        "category": Products.KEYCHAIN,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905270/taeType1Keychain_i9mmiz.jpg"],
        "members": [Bias.V],
        "description": "A classic and stylish keychain that captures V's unique and sophisticated charm. The 'Type 1' design is a must-have for any collection."
    },
    {
        "id": 35,
        "name": "Phone Charm Holder",
        "category": Products.OTHER,
        "price": 90,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905241/charmHolder_ma6zwl.png"],
        "members": [Bias.OT7],
        "description": "Personalize your phone and keep your favorite charms close with this versatile Phone Charm Holder. A practical and cute way to carry a piece of BTS with you."
    },
    {
        "id": 36,
        "name": "Jimin 3in1 Stand",
        "category": Products.STANDEE,
        "price": 420,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905255/jimin3in1Stand_faeyov.jpg"],
        "members": [Bias.JIMIN],
        "description": "Celebrate the multifaceted talent of Jimin with this stunning 3-in-1 standee. A beautiful and dynamic piece for your collection."
    },
    {
        "id": 37,
        "name": "Tae 3in1 Stand",
        "category": Products.STANDEE,
        "price": 420,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905264/tae3in1Stand_xyz0i1.jpg"],
        "members": [Bias.V],
        "description": "Capture the captivating presence of V from every angle. This 3-in-1 standee is the perfect centerpiece for any desk or shelf."
    },
    {
        "id": 38,
        "name": "JK 3in1 Stand",
        "category": Products.STANDEE,
        "price": 420,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905260/jk3in1Stande_pissee.jpg"],
        "members": [Bias.JUNGKOOK],
        "description": "A tribute to the Golden Maknae's incredible talents. This versatile and stunning JK 3-in-1 standee is a must-have for every fan."
    },
    {
        "id": 39,
        "name": "Tae Daddy Pin",
        "category": Products.STANDEE,
        "price": 280,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905265/taeDaddyPin_duqusx.png"],
        "members": [Bias.V],
        "description": "A playful and charming pin that captures V's charismatic and cool 'daddy' vibe. A fun and unique collectible for every adoring fan."
    },
    {
        "id": 40,
        "name": "RUN BTS Boat",
        "category": Products.STANDEE,
        "price": 450,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ['https://res.cloudinary.com/dxerpx7nt/image/upload/v1754908749/boatStandee_z4c0pu.png'],
        "members": [Bias.OT7],
        "description": "Relive the chaos and hilarity of the iconic 'RUN BTS' boat episode with this standee. A perfect piece of memorabilia for fans of their legendary variety show."
    },
    {
        "id": 41,
        "name": "TaeKook Memories Frame",
        "category": Products.OTHER,
        "price": 600,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905266/taeKookFrame_pnd9zb.png"],
        "members": [Bias.V, Bias.JUNGKOOK],
        "description": "Cherish the unforgettable moments between V and Jungkook with this beautiful 'Memories' frame. A perfect way to display your favorite TaeKook photocards."
    },
    {
        "id": 42,
        "name": "JiKook AYS Pin",
        "category": Products.ACRYLIC_PIN,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905254/jiKookAYSPin_mri7ru.png"],
        "members": [Bias.JIMIN, Bias.JUNGKOOK],
        "description": "The iconic 'Are you sure?' moment, now in a pin! This JiKook AYS Pin is a must-have for fans who love their playful and chaotic energy."
    },
    {
        "id": 43,
        "name": "Calendar 2025",
        "category": Products.OTHER,
        "price": 320,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754908749/calendar2025_1_mwe1yo.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905242/calendar2025_2_keek26.jpg"
        ],
        "members": [Bias.OT7],
        "description": "Stay organized and celebrate BTS all year long with the official 2025 Calendar. Featuring stunning photos of all seven members for every month."
    },
    {
        "id": 44,
        "name": "Magic Potion Holder",
        "category": Products.PC_HOLDER,
        "price": 420,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905247/magicPotion1_y8gnur.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905248/magicPotion2_cyhv7t.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905248/magicPotion3_yrngna.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905249/magicPotion4_wywzzo.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905249/magicPotion5_q4m8gh.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905249/magicPotion6_qzpz1h.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905250/magicPotionPCHolder_j326af.png"
        ],
        "members": [Bias.OT7],
        "description": "Brew up some love for BTS with this enchanting Magic Potion Photocard Holder. A whimsical and protective case for your treasured photocards."
    },
    {
        "id": 45,
        "name": "Magic Shop Keychain",
        "category": Products.KEYCHAIN,
        "price": 250,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905250/magicShopKeychain_gz6vn0.jpg"],
        "members": [Bias.OT7],
        "description": "Open the door to your own Magic Shop with this beautiful keychain. A comforting reminder that you're never alone, inspired by the beloved BTS song."
    },
    {
        "id": 46,
        "name": "Chibi Heads Accessory",
        "category": Products.KEYCHAIN,
        "price": 320,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905241/chibiHeadsAccessory1_indbul.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905242/chibiHeadsAccessory2_lhggqp.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905244/chibiHeadsAccessory13_mouvws.jpg"
        ],
        "members": [Bias.OT7],
        "description": "Add a dose of cuteness to your day with this Chibi Heads Accessory keychain! Featuring adorable chibi versions of all seven members, it's guaranteed to make you smile."
    },
    {
        "id": 47,
        "name": "Suga Guitar Keychain",
        "category": Products.KEYCHAIN,
        "price": 270,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905247/guitarKeychain1_dj04t9.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905248/guitarKeychain2_zdyvks.jpg"
        ],
        "members": [Bias.SUGA],
        "description": "Carry the soul of a rockstar with this Suga Guitar Keychain. A perfect tribute to his passion for music and his incredible guitar skills."
    },
    {
        "id": 48,
        "name": "Suga Guitar Keychain",
        "category": Products.KEYCHAIN,
        "price": 270,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905247/guitarKeychain1_dj04t9.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905248/guitarKeychain2_zdyvks.jpg"
        ],
        "members": [Bias.SUGA],
        "description": "Carry the soul of a rockstar with this Suga Guitar Keychain. A perfect tribute to his passion for music and his incredible guitar skills."
    },
    {
        "id": 49,
        "name": "Hobi Dior Pin",
        "category": Products.ACRYLIC_PIN,
        "price": 220,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905249/hobiDiorPin1_p1my7u.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905249/hobiDiorPin2_vaml1a.jpg"
        ],
        "members": [Bias.JHOPE],
        "description": "Celebrate J-Hope's iconic style with this chic Hobi Dior Pin. A fashionable and classy tribute to his stunning visuals and brand ambassadorship."
    },
    {
        "id": 50,
        "name": "JiKook AYS Standee",
        "category": Products.STANDEE,
        "price": 350,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905255/jiKookAYSStandee1_gjxhum.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905254/jiKookAYSStandee2_ddx1zy.jpg"
        ],
        "members": [Bias.JIMIN, Bias.JUNGKOOK],
        "description": "Bring the legendary 'Are you sure?' moment to your desk with this hilarious JiKook AYS Standee. A perfect display of their unique and chaotic bond."
    },
    {
        "id": 51,
        "name": "TaeKook Hawaii Standee",
        "category": Products.STANDEE,
        "price": 450,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905266/taeKookHawaiiStandee_b7bpva.jpg"],
        "members": [Bias.V, Bias.JUNGKOOK],
        "description": "Capture the beautiful memories of V and Jungkook in Hawaii with this scenic standee. A dreamy and romantic piece for all TaeKook shippers."
    },
    {
        "id": 52,
        "name": "Envy Koo Pin",
        "category": Products.KEYCHAIN,
        "price": 270,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905243/envyKoo_vuntti.jpg"],
        "members": [Bias.JUNGKOOK],
        "description": "A playful pin capturing Jungkook's envious side. This 'Envy Koo' pin is a fun and relatable piece for any devoted fan."
    },
    {
        "id": 53,
        "name": "Lovely Jin Keychain",
        "category": Products.KEYCHAIN,
        "price": 260,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905247/lovelyJinKeychain_kfmghz.jpg"],
        "members": [Bias.JIN],
        "description": "As lovely as Jin himself, this keychain is a charming accessory for any fan. A sweet and simple way to show your love for our Worldwide Handsome."
    },
    {
        "id": 54,
        "name": "TaeKook Hawaii Keychain",
        "category": Products.KEYCHAIN,
        "price": 260,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905266/taeKookHawaiiKeychain_jbdtey.jpg"],
        "members": [Bias.V, Bias.JUNGKOOK],
        "description": "Take a piece of paradise with you with this TaeKook Hawaii Keychain. A beautiful memento of their memorable trip, perfect for your keys or bag."
    },
    {
        "id": 55,
        "name": "JK Seven Keychain",
        "category": Products.KEYCHAIN,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905242/jkSevenKeychain_nhqqry.jpg"],
        "members": [Bias.JUNGKOOK],
        "description": "Celebrate Jungkook's global hit 'Seven' with this stylish keychain. A sleek and modern accessory for fans of the Golden Maknae's solo work."
    },
    {
        "id": 56,
        "name": "JITB Keychain",
        "category": Products.KEYCHAIN,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905261/jitbKeychain_i4lsrs.jpg"],
        "members": [Bias.JHOPE],
        "description": "Carry the explosive energy of J-Hope's 'Jack in the Box' album with you. This keychain is a bold statement piece for any fan of his groundbreaking solo music."
    },
    {
        "id": 57,
        "name": "Tae Layover Keychain",
        "category": Products.KEYCHAIN,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905268/taeLayoverKeychain_qotv5c.jpg"],
        "members": [Bias.V],
        "description": "Embrace the chill and soulful vibes of V's 'Layover' album with this keychain. A minimalist and artistic accessory for every fan."
    },
    {
        "id": 58,
        "name": "Namjoon Brain Charm",
        "category": Products.OTHER,
        "price": 80,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905257/namjoonBrainCharm_rcjj1i.jpg"],
        "members": [Bias.RM],
        "description": "A charming tribute to our genius leader, RM. This 'Namjoon Brain Charm' is a quirky and fun accessory for those who admire his brilliant mind."
    },
    {
        "id": 59,
        "name": "Muse Standee",
        "category": Products.STANDEE,
        "price": 350,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905257/museStandee_ogybrw.png"],
        "members": [Bias.JIMIN],
        "description": "Let Jimin be your muse with this elegant standee inspired by his solo album. A beautiful and artistic piece to adorn your space."
    },
    {
        "id": 60,
        "name": "Suga Valentino Pin",
        "category": Products.ACRYLIC_PIN,
        "price": 220,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905264/sugaValentinoPin_u66ha2.png"],
        "members": [Bias.SUGA],
        "description": "Elegance and edge combined. This Suga Valentino Pin celebrates his role as a brand ambassador, perfect for the fashion-forward ARMY."
    },
    {
        "id": 61,
        "name": "JiKook AYS Keychain",
        "category": Products.KEYCHAIN,
        "price": 300,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905253/jiKookAYSKeychain1_fbbobl.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905253/jiKookAYSKeychain_gck79v.png"
        ],
        "members": [Bias.JIMIN, Bias.JUNGKOOK],
        "description": "Take the iconic 'Are you sure?' moment with you wherever you go with this JiKook AYS Keychain. A fun and portable tribute to their chaotic friendship."
    },
    {
        "id": 62,
        "name": "Pin Holder Standee",
        "category": Products.STANDEE,
        "price": 250,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905258/pinHolderStandee_zbf9r2.png"],
        "members": [Bias.OT7],
        "description": "Display your favorite BTS pins in style with this sleek Pin Holder Standee. The perfect way to showcase your collection and love for the members."
    },
    {
        "id": 63,
        "name": "JiKook BlackSwan Standee",
        "category": Products.STANDEE,
        "price": 420,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905255/jiKookBlackSwanStandee_fhtehd.jpg"],
        "members": [Bias.JIMIN, Bias.JUNGKOOK],
        "description": "Capture the breathtaking artistry of Jimin and Jungkook's 'Black Swan' performance with this stunning standee. A graceful and elegant tribute to their powerful dance."
    },
    {
        "id": 64,
        "name": "Namjoon Brain Keychain",
        "category": Products.KEYCHAIN,
        "price": 420,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905258/namjoonBrainKeychain_vhd22r.jpg"],
        "members": [Bias.RM],
        "description": "A keychain for our brilliant leader. This Namjoon Brain Keychain is a fun and smart accessory, celebrating his incredible intellect and leadership."
    },
    {
        "id": 65,
        "name": "RM Saxophone Pin",
        "category": Products.ACRYLIC_PIN,
        "price": 220,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905260/rmSaxophonePin_vmwj1n.jpg"],
        "members": [Bias.RM],
        "description": "A fun and quirky pin celebrating RM's... unique saxophone skills. A must-have for ARMYs who love his playful and humorous side."
    },
    {
        "id": 66,
        "name": "Tae Broken Holo Keychain",
        "category": Products.KEYCHAIN,
        "price": 300,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905264/taeCartierKeychain_lgwe2z.jpg"],
        "members": [Bias.V],
        "description": "A dazzling holographic keychain with a unique 'broken' glass effect. This Tae Broken Holo Keychain is a stylish and eye-catching accessory for any V fan."
    },
    {
        "id": 67,
        "name": "TaeKook Rotating Standee",
        "category": Products.STANDEE,
        "price": 420,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905268/taeKookRotatingStandee_livn1y.jpg"],
        "members": [Bias.V, Bias.JUNGKOOK],
        "description": "Double the love with this TaeKook Rotating Standee. Featuring a different image on each side, you can switch up your display to match your mood."
    },
    {
        "id": 68,
        "name": "VMin Mini Pin",
        "category": Products.ACRYLIC_PIN,
        "price": 120,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905272/vMinMiniPin_wwbmk3.png"],
        "members": [Bias.V, Bias.JIMIN],
        "description": "A mini pin to celebrate the soulmate bond of VMin. This cute and subtle accessory is perfect for showcasing your love for this iconic duo."
    },
    {
        "id": 69,
        "name": "RAP Line Keychain",
        "category": Products.KEYCHAIN,
        "price": 300,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905260/rapLineKeychain_z4g7ga.png"],
        "members": [Bias.RM, Bias.SUGA, Bias.JHOPE],
        "description": "Celebrate the powerful RAP line with this dynamic keychain. A perfect accessory for fans of RM, SUGA, and J-Hope's incredible talent."
    },
    {
        "id": 70,
        "name": "JK-BAM Standee",
        "category": Products.STANDEE,
        "price": 300,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905261/jkBamStandee_xq2djk.jpg"],
        "members": [Bias.JUNGKOOK],
        "description": "A heartwarming standee featuring Jungkook and his beloved dog, Bam. A must-have for any ARMY who adores their sweet bond."
    },
    {
        "id": 71,
        "name": "HOTS Standee",
        "category": Products.STANDEE,
        "price": 300,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905255/hotsStandee_uhhfcw.png"],
        "members": [Bias.JHOPE],
        "description": "Bring the fire of J-Hope's 'on the street' style to your room with this HOTS Standee. A vibrant and energetic display for our dance leader."
    },
    {
        "id": 72,
        "name": "Tae Friends Standee",
        "category": Products.STANDEE,
        "price": 300,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905269/taeFriendsStandee_lcbiae.png"],
        "members": [Bias.V],
        "description": "Celebrate the beautiful bond of friendship with this Tae 'Friends' Standee. A heartwarming tribute to his solo song and his cherished connection with Jimin."
    },
    {
        "id": 73,
        "name": "Euphoria Pin",
        "category": Products.ACRYLIC_PIN,
        "price": 250,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905244/euphoriaPin1_zolfdt.png",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905245/euphoriaPin2_sxfkma.png"
        ],
        "members": [Bias.JUNGKOOK],
        "description": "Capture the blissful feeling of 'Euphoria' with this beautiful pin. A dreamy and uplifting accessory for all Jungkook fans."
    },
    {
        "id": 74,
        "name": "Tae Cartier Pin",
        "category": Products.ACRYLIC_PIN,
        "price": 250,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905265/taeCartierPin_bpmzzq.png"],
        "members": [Bias.V],
        "description": "Exude elegance with this Tae Cartier Pin. A sophisticated and stylish tribute to V's role as a global brand ambassador."
    },
    {
        "id": 75,
        "name": "Tae Bazaar Pin",
        "category": Products.ACRYLIC_PIN,
        "price": 250,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905264/taeBazaarPin_mzu737.png"],
        "members": [Bias.V],
        "description": "A pin that captures V's high-fashion moment from his Bazaar cover shoot. A stunning and fashionable collectible for any V bias."
    },
    {
        "id": 76,
        "name": "D-DAY Standee",
        "category": Products.STANDEE,
        "price": 300,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905247/ddayStandee_u669kr.png"],
        "members": [Bias.SUGA],
        "description": "Commemorate Suga's powerful 'D-DAY' album and tour with this striking standee. A must-have piece for fans of Agust D."
    },
    {
        "id": 77,
        "name": "Face Standee",
        "category": Products.STANDEE,
        "price": 300,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905248/faceStandee_trcp8e.png"],
        "members": [Bias.JIMIN],
        "description": "Capture the raw emotion and artistry of Jimin's 'Face' album with this stunning standee. A beautiful and introspective piece for your collection."
    },
    {
        "id": 78,
        "name": "Indigo Standee",
        "category": Products.STANDEE,
        "price": 300,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905253/indigoStandee_ltsvpn.png"],
        "members": [Bias.RM],
        "description": "Bring the calm, artistic vibes of RM's 'Indigo' into your space with this beautiful standee. A tribute to his last archive of his twenties."
    },
    {
        "id": 79,
        "name": "Mini Army Bomb",
        "category": Products.STANDEE,
        "price": 420,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905255/miniArmyBomb_zdihgc.png"],
        "members": [Bias.OT7],
        "description": "Light up your love for BTS with this adorable Mini Army Bomb Standee. A perfect miniature version of the iconic light stick for your desk or shelf."
    },
    {
        "id": 80,
        "name": "TaeKook Date Keychain",
        "category": Products.KEYCHAIN,
        "price": 450,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905266/taeKookDateKeychain_yzdhbt.png"],
        "members": [Bias.V, Bias.JUNGKOOK],
        "description": "Capture the sweetness of a TaeKook date with this adorable keychain. A romantic and charming accessory for all shippers."
    },
    {
        "id": 81,
        "name": "Suga Tattoo Reveal Keychain",
        "category": Products.KEYCHAIN,
        "price": 300,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905263/sugaTattooReveal_k49xbm.png"],
        "members": [Bias.SUGA],
        "description": "A keychain celebrating the iconic moment of Suga revealing his '7' friendship tattoo. A meaningful and personal piece for any ARMY."
    },
    {
        "id": 82,
        "name": "JITB Standee",
        "category": Products.STANDEE,
        "price": 300,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905259/jitbStandee1_lcwhy8.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905262/jitbStandee2_whksrf.jpg"
        ],
        "members": [Bias.JHOPE],
        "description": "Unleash the creativity of J-Hope's 'Jack in the Box' with this dynamic standee. A bold and artistic display piece for your collection."
    },
    {
        "id": 83,
        "name": "Golden Standee",
        "category": Products.STANDEE,
        "price": 300,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": [
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905246/goldenStandee1_vvvuw6.jpg",
            "https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905246/goldenStandee2_a0lrhl.jpg"
        ],
        "members": [Bias.JUNGKOOK],
        "description": "Celebrate the 'Golden' era of Jungkook with this stunning standee. A shining tribute to the Golden Maknae's solo album."
    },
    {
        "id": 84,
        "name": "Koo In Towel",
        "category": Products.ACRYLIC_PIN,
        "price": 200,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905247/kooInTowel_kn0v4w.png"],
        "members": [Bias.JUNGKOOK],
        "description": "A cheeky and charming pin featuring Jungkook wrapped in a towel. A fun and flirty collectible for the devoted Koo fan."
    },
    {
        "id": 85,
        "name": "Tae WinterBear Pin",
        "category": Products.ACRYLIC_PIN,
        "price": 200,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905271/taeWinterBearPin_nlmuz9.png"],
        "members": [Bias.V],
        "description": "Wear the warmth and gentleness of 'Winter Bear' with this beautiful pin. A cozy and artistic accessory inspired by V's heartfelt song."
    },
    {
        "id": 86,
        "name": "TaeKook Holo Keychain",
        "category": Products.KEYCHAIN,
        "price": 300,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905271/taeKookkeychain_co1vdt.png"],
        "members": [Bias.V, Bias.JUNGKOOK],
        "description": "A dazzling holographic keychain celebrating the bond of TaeKook. Watch the colors shift and shine, just like their dynamic friendship."
    },
    {
        "id": 87,
        "name": "V Celine Pin",
        "category": Products.ENAMEL_PIN,
        "price": 400,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905271/vCelinePin_x5l9ne.png"],
        "members": [Bias.V],
        "description": "Showcase V's impeccable style with this elegant Celine pin. A chic and fashionable accessory for fans of his iconic brand partnership."
    },
    {
        "id": 88,
        "name": "Astronaut Standee",
        "category": Products.STANDEE,
        "price": 300,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905258/jinAstronautStandee_jqncwj.png"],
        "members": [Bias.JIN],
        "description": "Explore the cosmos with Jin and this 'Astronaut' Standee. A beautiful tribute to his heartfelt solo song for ARMY."
    },
    {
        "id": 89,
        "name": "Kookie Pin",
        "category": Products.ENAMEL_PIN,
        "price": 500,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905242/jkPin_yb2hui.png"],
        "members": [Bias.JUNGKOOK],
        "description": "A cute and classic enamel pin to show your love for Kookie. A must-have for any Jungkook bias's collection."
    },
    {
        "id": 90,
        "name": "Tae Pin",
        "category": Products.ENAMEL_PIN,
        "price": 500,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ['https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905275/vPin_uhlmcl.png'],
        "members": [Bias.V],
        "description": "An elegant enamel pin that captures the unique charm of V. A simple yet beautiful accessory for any Tae fan."
    },
    {
        "id": 91,
        "name": "Jimine Pin",
        "category": Products.ENAMEL_PIN,
        "price": 500,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905260/jiminPin_vlozdp.png"],
        "members": [Bias.JIMIN],
        "description": "A lovely enamel pin dedicated to our charming Jimine. A perfect and pretty addition to your pin collection."
    },
    {
        "id": 92,
        "name": "Hobi Pin",
        "category": Products.ENAMEL_PIN,
        "price": 500,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905255/hobiPin_edi9xr.png"],
        "members": [Bias.JHOPE],
        "description": "Bring a ray of sunshine to your day with this Hobi enamel pin. A bright and cheerful accessory, just like J-Hope himself."
    },
    {
        "id": 93,
        "name": "Yoongi Pin",
        "category": Products.ENAMEL_PIN,
        "price": 500,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905265/sugaPin_mdrivf.png"],
        "members": [Bias.SUGA],
        "description": "A cool and stylish enamel pin for our genius, Yoongi. A subtle yet powerful way to show your love for Suga."
    },
    {
        "id": 94,
        "name": "Jinnie Pin",
        "category": Products.ENAMEL_PIN,
        "price": 500,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905259/jinPin_ttvmz2.png"],
        "members": [Bias.JIN],
        "description": "A handsome enamel pin for our Worldwide Handsome, Jinnie. A perfect piece to celebrate his charm and humor."
    },
    {
        "id": 95,
        "name": "Joonie Pin",
        "category": Products.ENAMEL_PIN,
        "price": 500,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905260/rmPin_eicvc8.png"],
        "members": [Bias.RM],
        "description": "An intelligent and thoughtful enamel pin for our leader, Joonie. A sophisticated accessory for any fan of RM."
    },
    {
        "id": 96,
        "name": "JK Fofo Standee",
        "category": Products.STANDEE,
        "price": 250,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905242/jkFofo_szjlmj.png"],
        "members": [Bias.JK],
        "description": "Add a dose of cuteness to your space with the JK Fofo Standee. An adorable and playful display of our Golden Maknae."
    },
    {
        "id": 97,
        "name": "V Fofo Standee",
        "category": Products.STANDEE,
        "price": 250,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905272/vFofo_pweoap.png"],
        "members": [Bias.V],
        "description": "Cuteness and charm combined in the V Fofo Standee. A sweet and endearing collectible for every V fan."
    },
    {
        "id": 98,
        "name": "Jimin Fofo Standee",
        "category": Products.STANDEE,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905257/jiminFofo_yw4z56.png"],
        "members": [Bias.JIMIN],
        "description": "The Jimin Fofo Standee is here to melt your heart. An irresistibly cute and charming addition to your collection."
    },
    {
        "id": 99,
        "name": "Jhope Fofo Standee",
        "category": Products.STANDEE,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905250/hobiFofo_uvldqx.png"],
        "members": [Bias.JHOPE],
        "description": "Brighten up your room with the J-Hope Fofo Standee. A cheerful and adorable piece that captures his sunshine energy."
    },
    {
        "id": 100,
        "name": "Suga Fofo Standee",
        "category": Products.STANDEE,
        "price": 250,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905265/sugaFofo_mpr3nf.png"],
        "members": [Bias.SUGA],
        "description": "Even in 'fofo' form, Suga's coolness shines. This cute standee is a must-have for every Yoongi stan."
    },
    {
        "id": 101,
        "name": "Jin Fofo Standee",
        "category": Products.STANDEE,
        "price": 250,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905259/jinFofo_oyjjhp.png"],
        "members": [Bias.JIN],
        "description": "Worldwide Handsome, now in adorable Fofo form! The Jin Fofo Standee is a charming and cute collectible."
    },
    {
        "id": 102,
        "name": "RM Fofo Standee",
        "category": Products.STANDEE,
        "price": 250,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905260/rmFofo_eglthw.png"],
        "members": [Bias.RM],
        "description": "Our genius leader in a cute and cuddly Fofo style. The RM Fofo Standee is a unique and charming piece for your desk."
    },
    {
        "id": 103,
        "name": "Fofo Standee Set",
        "category": Products.STANDEE,
        "price": 1500,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905250/fofoStandeeSet_npcu7f.png"],
        "members": [Bias.OT7],
        "description": "Get the complete collection of cuteness with the Fofo Standee Set! Featuring all seven members in this adorable style, it's the perfect set for any ARMY."
    },
    {
        "id": 104,
        "name": "Jimin Moon Keychain",
        "category": Products.KEYCHAIN,
        "price": 250,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905256/jiminMoonKeychain_eg6t2e.png"],
        "members": [Bias.JIMIN],
        "description": "Inspired by Jimin's beautiful and symbolic moon tattoo, this keychain is a delicate and meaningful accessory for any fan."
    },
    {
        "id": 105,
        "name": "Jimin SetMeFree Keychain",
        "category": Products.KEYCHAIN,
        "price": 250,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905263/jiminSetMeFreeKeychain_zvsfps.png"],
        "members": [Bias.JIMIN],
        "description": "Unleash your passion with this 'Set Me Free Pt.2' keychain. A powerful and artistic accessory inspired by Jimin's explosive solo track."
    },
    {
        "id": 106,
        "name": "Jimin Face Keychain",
        "category": Products.KEYCHAIN,
        "price": 250,
        "currency": "INR",
        "inStock": false,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905259/jiminFaceKeychain_xm8wuq.png"],
        "members": [Bias.JIMIN],
        "description": "Carry the artistry of Jimin's 'Face' album with you. This keychain is a stylish and meaningful tribute to his solo debut."
    },
    {
        "id": 107,
        "name": "JK CK",
        "category": Products.ENAMEL_PIN,
        "price": 500,
        "currency": "INR",
        "inStock": true,
        "stock": 20,
        "images": ["https://res.cloudinary.com/dxerpx7nt/image/upload/v1754905262/jkckPin_ifiys7.png"],
        "members": [Bias.JUNGKOOK],
        "description": "Celebrate Jungkook's iconic Calvin Klein campaign with this stylish enamel pin. A must-have collectible for fans of his stunning visuals."
    }
];

export default products;